# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: s_parent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='s_parent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0es_parent.proto\"\xbf\x01\n\x0eSearchService2\x1a\x66\n\rCommonRequest\x12\x14\n\x0cresourcetype\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07referer\x18\x03 \x01(\t\x12\r\n\x05md5id\x18\x04 \x01(\t\x12\x13\n\x0btransaction\x18\x05 \x01(\t\x1a\x45\n\rSearchRequest\x12\x34\n\rcommonrequest\x18\x01 \x01(\x0b\x32\x1d.SearchService2.CommonRequestb\x06proto3'
)




_SEARCHSERVICE2_COMMONREQUEST = _descriptor.Descriptor(
  name='CommonRequest',
  full_name='SearchService2.CommonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resourcetype', full_name='SearchService2.CommonRequest.resourcetype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='SearchService2.CommonRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='referer', full_name='SearchService2.CommonRequest.referer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5id', full_name='SearchService2.CommonRequest.md5id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='SearchService2.CommonRequest.transaction', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=139,
)

_SEARCHSERVICE2_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='SearchService2.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commonrequest', full_name='SearchService2.SearchRequest.commonrequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=210,
)

_SEARCHSERVICE2 = _descriptor.Descriptor(
  name='SearchService2',
  full_name='SearchService2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_SEARCHSERVICE2_COMMONREQUEST, _SEARCHSERVICE2_SEARCHREQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=210,
)

_SEARCHSERVICE2_COMMONREQUEST.containing_type = _SEARCHSERVICE2
_SEARCHSERVICE2_SEARCHREQUEST.fields_by_name['commonrequest'].message_type = _SEARCHSERVICE2_COMMONREQUEST
_SEARCHSERVICE2_SEARCHREQUEST.containing_type = _SEARCHSERVICE2
DESCRIPTOR.message_types_by_name['SearchService2'] = _SEARCHSERVICE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchService2 = _reflection.GeneratedProtocolMessageType('SearchService2', (_message.Message,), {

  'CommonRequest' : _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE2_COMMONREQUEST,
    '__module__' : 's_parent_pb2'
    # @@protoc_insertion_point(class_scope:SearchService2.CommonRequest)
    })
  ,

  'SearchRequest' : _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE2_SEARCHREQUEST,
    '__module__' : 's_parent_pb2'
    # @@protoc_insertion_point(class_scope:SearchService2.SearchRequest)
    })
  ,
  'DESCRIPTOR' : _SEARCHSERVICE2,
  '__module__' : 's_parent_pb2'
  # @@protoc_insertion_point(class_scope:SearchService2)
  })
_sym_db.RegisterMessage(SearchService2)
_sym_db.RegisterMessage(SearchService2.CommonRequest)
_sym_db.RegisterMessage(SearchService2.SearchRequest)


# @@protoc_insertion_point(module_scope)
